env:
  browser: true
  es2021: true
extends:
  - plugin:react/recommended
  - plugin:react-hooks/recommended
  - standard-with-typescript
  # extendsの読み込みは上から順に上書きされていくので、この設定は最後に書くこと
  - prettier
  - plugin:@tanstack/eslint-plugin-query/recommended
overrides: []
parserOptions:
  ecmaVersion: latest
  sourceType: module
  project: ./tsconfig.json
plugins:
  - react
  - unused-imports
  - import
  - "@tanstack/query"
ignorePatterns:
  - vite.config.ts
  - vitest.setup.ts
rules:
  "@tanstack/query/exhaustive-deps": error
  "@tanstack/query/prefer-query-object-syntax": error
  react/react-in-jsx-scope: off
  "@typescript-eslint/triple-slash-reference": off
  "@typescript-eslint/consistent-type-definitions": off
  react/no-unknown-property:
    - error
    - ignore: [css]
  unused-imports/no-unused-imports: "error"
  indent:
    - 1
  import/newline-after-import:
    - error
    - count: 3
  import/order:
    - error
    - groups:
        - builtin
        - external
        - internal
        -
          - parent
          - sibling
        - object
        - type
        - index
      newlines-between: always
      pathGroupsExcludedImportTypes:
        - builtin
      alphabetize:
        order: asc
        caseInsensitive: true
