env:
  browser: true
  es2021: true
extends:
  - plugin:react/recommended
  - plugin:react-hooks/recommended
  - standard-with-typescript
  # extendsの読み込みは上から順に上書きされていくので、この設定は最後に書くこと
  - prettier
overrides: []
parserOptions:
  ecmaVersion: latest
  sourceType: module
  project: ./tsconfig.json
plugins:
  - react
  - unused-imports
  - import
  - import-newlines
ignorePatterns:
  - vite.config.ts
  - vitest.setup.ts
rules:
  "react/react-in-jsx-scope": "off"
  "@typescript-eslint/triple-slash-reference": "off"
  "@typescript-eslint/consistent-type-definitions": "off"
  "react/no-unknown-property": ["error", { "ignore": ["css"] }]
  "unused-imports/no-unused-imports": "error"
  import-newlines/enforce:
    - error
    -
      items: 2
      semi: false
      forceSingleLine: false
  indent:
      - 1
  import/order:
    - error
    - groups:
        - builtin
        - external
        - internal
        - parent
        - sibling
        - object
        - type
        - index
      newlines-between: always
      pathGroupsExcludedImportTypes:
        - builtin
      alphabetize:
        order: asc
        caseInsensitive: true
