name: CD
on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
  workflow_dispatch:

env:
  NODE_VERSION: '16.x'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'

    - name: npm install, build
      run: |
        npm install
        npm run build

  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - id: 'auth'
      uses: 'google-github-actions/auth@v1'
      with:
        workload_identity_provider: ${{ secrets.GCP_IAM_PROVIDER }}
        service_account: ${{ secrets.CP_SERVICE_ACCOUNT }}


  # upload_file_gcs:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #     - uses: google-github-actions/setup-gcloud@master
  #       with:
  #         project_id: ${{ secrets.GCP_PROJECT_ID }}
  #         service_account_key: ${{ secrets.GCP_SA_KEY }}
  #         export_default_credentials: true
  #     # - name: create zip
  #     #   working-directory: ./
  #     #   run: zip -r ./functions.zip ./functions/function.go ./go.mod
  #     - id: upload-file
  #       uses: google-github-actions/upload-cloud-storage@main
  #       with:
  #         path: ./functions.zip
  #         destination: bucket_name/functions
